### PR TITLE
CI for `dev-1deg_jra55do_ryf`

### PR DESCRIPTION
**Pull request by CodeGat**
In this PR:
* Add the CI from `main` in https://github.com/ACCESS-NRI/access-om3-wav-configs/tree/4ed06889139ee6a8d85f9bbd7611d74aa688e4d1/.github/workflows

References #55

### CODE REVIEW

**Comment by CodeGat** [comment]
!cherry-pick https://github.com/ACCESS-NRI/access-om3-wav-configs/pull/59/commits/14dd94ae1182bc50b94c11ec4780501ad00f3f94 into dev-1deg_jra55do_iaf

**Review by anton-seaice — APPROVED** [review]

**Comment by CodeGat** [comment]
!cherry-pick https://github.com/ACCESS-NRI/access-om3-wav-configs/commit/14dd94ae1182bc50b94c11ec4780501ad00f3f94 into dev-1deg_jra55do_iaf

**Comment by CodeGat** [comment]
!cherry-pick https://github.com/ACCESS-NRI/access-om3-wav-configs/commit/bd08739afb796a7ade4a30b11cc89487c8ceb4e6 into dev-1deg_jra55do_iaf

**Comment by CodeGat** [comment]
!cherry-pick bd08739afb796a7ade4a30b11cc89487c8ceb4e6 into dev-1deg_jra55do_iaf

**Pull request merged**
