### PR TITLE
Dev 1deg jra55do ryf cherrypicks

### PR DESCRIPTION
**Pull request by anton-seaice**
Cherry-picks from the om3-configs branch as described in the commits

### CODE REVIEW

**Comment by anton-seaice** [comment]
I ran this and it started

**Comment by anton-seaice** [comment]
@ezhilsabareesh8 - Can you have a look at this ?

**Comment by ezhilsabareesh8** [comment]
> Can you have a look at this ?

I am doing a test run right now, will update shortly.

**Review by ezhilsabareesh8 — APPROVED** [review]
Thanks @anton-seaice, it looks good to me and test runs are fine.

**Pull request merged**
